=IF(B5=0, "Error", IFERROR(SUMPRODUCT(('WORK DRIVER'!CQ:CQ=C5)*ISNUMBER(MATCH('WORK DRIVER'!CV:CV, {"MRM Tasks","OMRs","RAIs","RMs"}, 0))*N('WORK DRIVER'!GC:GC))/B5, "Error"))
=IF(B5=0, "Error", IFERROR(SUMPRODUCT(('WORK DRIVER'!CQ$2:CQ$1000=C5)*ISNUMBER(MATCH('WORK DRIVER'!CV$2:CV$1000, {"MRM Tasks","OMRs","RAIs","RMs"}, 0))*N('WORK DRIVER'!GC$2:GC$1000))/B5, "Error"))


IFERROR(IF(B5=0, "Error", SUMPRODUCT(('WORK DRIVER'!CQ:CQ=C5)*ISNUMBER(MATCH('WORK DRIVER'!CV:CV, {"MRM Tasks","OMRs","RAIs","RMs"}, 0))*N('WORK DRIVER'!GC:GC))/B5), "Error")